version: '2'

services:
   devcontainer:
     container_name: sdtdserver
     build:
       context: .
     volumes:
       - ./data/sdtdserver:/sdtdserver
     restart: unless-stopped
     command: tail -F anything
     ports:
           - "8080:8080"
           - "8081:8081"
           - "8082:8082"
           - "26900:26900"
           - "26901:26901"
           - "26902:26902"
     environment:
       - TEST_VAR=Dies ist ein Test
